-- PostGISイメージの10_postgis.shが拡張を有効化した後に実行するため、ファイル名を20で始める。
-- location列のgeography型と、座標変換に使うST_*関数はPostGISが提供する。
BEGIN;

CREATE TABLE spots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category text NOT NULL,
    address text NOT NULL,
    location geography(Point, 4326) NOT NULL
);

-- PostGISが範囲外の座標を補正する前に、CSVの値を検証する。
CREATE TEMP TABLE spot_seed (
    name text NOT NULL CHECK (btrim(name, E' \t\r\n') <> ''),
    category text NOT NULL CHECK (btrim(category, E' \t\r\n') <> ''),
    lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
    long double precision NOT NULL CHECK (long BETWEEN -180 AND 180),
    address text NOT NULL CHECK (btrim(address, E' \t\r\n') <> '')
) ON COMMIT DROP;

COPY spot_seed (name, category, lat, long, address)
FROM '/seed/landit_coding_test_seed.csv'
WITH (FORMAT csv, HEADER MATCH);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM spot_seed) THEN
        RAISE EXCEPTION 'Spot seed CSV contains no data rows';
    END IF;
END
$$;

INSERT INTO spots (name, category, address, location)
SELECT name, category, address,
       ST_SetSRID(ST_MakePoint(long, lat), 4326)::geography
FROM spot_seed;

CREATE INDEX spots_location_idx ON spots USING GIST (location);

COMMIT;
