import type { MigrationInterface, QueryRunner } from "typeorm";

export class CreateSpots1788672000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE EXTENSION IF NOT EXISTS postgis");
    await queryRunner.query(`
      CREATE TABLE spots (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        category text NOT NULL,
        address text NOT NULL,
        location geography(Point, 4326) NOT NULL
      )
    `);
    await queryRunner.query(
      "CREATE INDEX spots_location_idx ON spots USING GIST (location)",
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("DROP TABLE spots");
    // PostGISは他のテーブルやイメージの初期設定でも使われるため残す。
  }
}
